#!/bin/bash

cd
$(git clone "socpub@ecegrid.ecn.purdue.edu:SoCET_Public.git")
cd "~/SoCET_Public/"
$(git submodule init)
$(git submodule update)
cd "~/SoCET_Public/RISCVBusiness/"
$(python2.6 "scripts/config_core.py" sparce.yml)
cd "~/SoCET_Public/"
#cp ".bashrc" "~/"
#$(sed -i s/socet02/$(whoami)/g ~/SoCET_Public/.bashrc)
#cp ".bash_profile" "~/"
#cp "init_vlsi" "~/"
$(git checkout aftx05_ahb_apb)
$(ssh-copy-id socetlnx03@128.46.75.147)
#type: "yes"
#type: "socetuser2019!"